spring:
  application:
    name: skillifymepayment
  data:
    mongodb:
      uri: ${mongo_uri}
      database: SkillifyMe
      auto-index-creation: true
      username: ${mongo_password}
      password: ${mongo_password}
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

paypal:
  client-id: ${client_id}
  client-secret: ${client_secret}
  mode: sandbox
  success:
    url: http://localhost:8082/api/payments/payment-success
  cancel:
    url: http://localhost:8082/api/payments/cancel